interface Props { id: string; }

export function TemplateThumbnail({ id }: Props) {
  switch (id) {
    case 'classic': return <div className="flex h-full rounded overflow-hidden"><div className="w-[30%] bg-blue-200/60" /><div className="flex-1 p-1 space-y-0.5"><div className="h-1 bg-slate-300 rounded w-3/4" /><div className="h-0.5 bg-slate-200 rounded" /></div></div>;
    case 'modern': return <div className="flex flex-col h-full p-1 space-y-0.5"><div className="h-1 bg-slate-400 w-1/2 rounded mx-auto" /><div className="h-px bg-slate-300" /><div className="space-y-0.5"><div className="h-0.5 bg-slate-200 rounded" /><div className="h-0.5 bg-slate-200 rounded w-3/4" /></div></div>;
    case 'minimal': return <div className="flex flex-col h-full p-1 space-y-1"><div className="h-1 bg-slate-500 w-1/3 rounded" /><div className="h-px bg-slate-300" /><div className="h-0.5 bg-slate-300 rounded w-5/6" /><div className="h-0.5 bg-slate-300 rounded w-4/6" /></div>;
    case 'sidebar': return <div className="flex h-full rounded overflow-hidden"><div className="w-[30%] bg-slate-700" /><div className="flex-1 p-1 space-y-0.5 bg-white"><div className="h-1 bg-slate-300 rounded w-3/4" /><div className="h-0.5 bg-slate-200 rounded" /></div></div>;
    case 'double': return <div className="flex flex-col h-full"><div className="h-[25%] bg-slate-200 p-0.5"><div className="h-1 bg-slate-400 w-1/3 mx-auto rounded" /></div><div className="flex flex-1"><div className="flex-1 p-0.5 space-y-0.5 border-r border-slate-200"><div className="h-0.5 bg-slate-300 rounded" /></div><div className="flex-1 p-0.5"><div className="h-0.5 bg-slate-300 rounded" /></div></div></div>;
    case 'timeline': return <div className="flex h-full p-1"><div className="w-1 bg-slate-400/30 rounded-full mr-1.5" /><div className="flex-1 space-y-0.5"><div className="h-1 bg-slate-400 rounded w-1/2 mb-1" /><div className="flex gap-0.5"><div className="w-[25%] h-0.5 bg-slate-300 rounded" /><div className="flex-1 h-0.5 bg-slate-200 rounded" /></div><div className="flex gap-0.5"><div className="w-[25%] h-0.5 bg-slate-300 rounded" /><div className="flex-1 h-0.5 bg-slate-200 rounded" /></div></div></div>;
    case 'compact': return <div className="flex flex-col h-full p-0.5"><div className="flex justify-between mb-0.5"><div className="h-1 bg-slate-400 w-1/3 rounded" /><div className="flex gap-0.5"><div className="h-0.5 bg-slate-300 w-3 rounded" /><div className="h-0.5 bg-slate-300 w-3 rounded" /></div></div><div className="grid grid-cols-2 gap-0.5 flex-1"><div className="h-0.5 bg-slate-200 rounded" /><div className="h-0.5 bg-slate-200 rounded" /></div></div>;
    case 'executive': return <div className="flex flex-col h-full p-1 items-center"><div className="h-1.5 bg-slate-500 w-1/2 rounded mb-1" /><div className="h-px bg-slate-400 w-full mb-0.5" /><div className="h-0.5 bg-slate-200 rounded w-5/6" /><div className="h-px bg-slate-400 w-full my-0.5" /><div className="h-0.5 bg-slate-200 rounded w-3/4" /></div>;
    default: return <div className="flex h-full items-center justify-center"><div className="h-1 bg-slate-300 w-1/2 rounded" /></div>;
  }
}
